export enum ErrorCodes {
  INVALID_JSON = "INVALID_JSON",
  INVALID_CONTENT_TYPE = "INVALID_CONTENT_TYPE",
  BAD_REQUEST = "BAD_REQUEST",
  NOT_FOUND = "NOT_FOUND",
  RAW_BODY_REQUIRED = "RAW_BODY_REQUIRED",
  REJECTION_REASON_REQUIRED = "REJECTION_REASON_REQUIRED",
  MISSING_SIGNATURE = "MISSING_SIGNATURE",
  INVALID_SIGNATURE = "INVALID_SIGNATURE",
  UNAUTHORIZED = "UNAUTHORIZED",
  CONFIG_ERROR = "CONFIG_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  DEPOSIT_ONLY_BASKET_CURRENCIES = "DEPOSIT_ONLY_BASKET_CURRENCIES",
  INVALID_CURRENCY = "INVALID_CURRENCY",
  DUPLICATE_FINTECH_TX_ID = "DUPLICATE_FINTECH_TX_ID",
  PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE",
  CIRCUIT_BREAKER = "CIRCUIT_BREAKER",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}

export type ErrorCode = keyof typeof ErrorCodes | string;
